apiVersion: v1
kind: Service 
metadata:
  name: myapp-pod-loadbalancer-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp # Important this selector should match the label in the pod definition
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port